name: CUGETDEAL

on:
  push:
    branches:
      - deploy-app
      # - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'

    - name: Install Dependencies
      run: |
        cd client
        npm install

    - name: Build
      run: |
        cd client
        npm run build

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages  # The branch the action should deploy to.
        FOLDER: client/build  # The folder the action should deploy.
        CLEAN: true
